/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Context",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Context__factory>;
    getContractFactory(
      name: "GSNRecipient",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GSNRecipient__factory>;
    getContractFactory(
      name: "IRelayHub",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRelayHub__factory>;
    getContractFactory(
      name: "IRelayRecipient",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRelayRecipient__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Detailed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Detailed__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "BaseAdminUpgradeabilityProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseAdminUpgradeabilityProxy__factory>;
    getContractFactory(
      name: "BaseUpgradeabilityProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseUpgradeabilityProxy__factory>;
    getContractFactory(
      name: "InitializableAdminUpgradeabilityProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InitializableAdminUpgradeabilityProxy__factory>;
    getContractFactory(
      name: "InitializableUpgradeabilityProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InitializableUpgradeabilityProxy__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "UpgradeabilityProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradeabilityProxy__factory>;
    getContractFactory(
      name: "BasicAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BasicAdapter__factory>;
    getContractFactory(
      name: "ERC20WithPermit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20WithPermit__factory>;
    getContractFactory(
      name: "ERC20WithRate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20WithRate__factory>;
    getContractFactory(
      name: "GatewayFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GatewayFactory__factory>;
    getContractFactory(
      name: "GatewayRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GatewayRegistry__factory>;
    getContractFactory(
      name: "IERC20Standard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Standard__factory>;
    getContractFactory(
      name: "IBurnGateway",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBurnGateway__factory>;
    getContractFactory(
      name: "IGateway",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGateway__factory>;
    getContractFactory(
      name: "IMintGateway",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMintGateway__factory>;
    getContractFactory(
      name: "IGatewayRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGatewayRegistry__factory>;
    getContractFactory(
      name: "BCHGateway",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BCHGateway__factory>;
    getContractFactory(
      name: "BTCGateway",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BTCGateway__factory>;
    getContractFactory(
      name: "MintGatewayLogicV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MintGatewayLogicV1__factory>;
    getContractFactory(
      name: "MintGatewayStateV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MintGatewayStateV1__factory>;
    getContractFactory(
      name: "ZECGateway",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZECGateway__factory>;
    getContractFactory(
      name: "MintGatewayLogicV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MintGatewayLogicV2__factory>;
    getContractFactory(
      name: "MintGatewayProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MintGatewayProxy__factory>;
    getContractFactory(
      name: "MintGatewayStateV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MintGatewayStateV2__factory>;
    getContractFactory(
      name: "RenERC20LogicV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RenERC20LogicV1__factory>;
    getContractFactory(
      name: "RenERC20Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RenERC20Proxy__factory>;
    getContractFactory(
      name: "Claimable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Claimable__factory>;
    getContractFactory(
      name: "CanReclaimTokens",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CanReclaimTokens__factory>;
    getContractFactory(
      name: "LinkedList",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LinkedList__factory>;
    getContractFactory(
      name: "Adapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Adapter__factory>;

    getContractAt(
      name: "Context",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Context>;
    getContractAt(
      name: "GSNRecipient",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GSNRecipient>;
    getContractAt(
      name: "IRelayHub",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IRelayHub>;
    getContractAt(
      name: "IRelayRecipient",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IRelayRecipient>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC20Detailed",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Detailed>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "BaseAdminUpgradeabilityProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseAdminUpgradeabilityProxy>;
    getContractAt(
      name: "BaseUpgradeabilityProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseUpgradeabilityProxy>;
    getContractAt(
      name: "InitializableAdminUpgradeabilityProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InitializableAdminUpgradeabilityProxy>;
    getContractAt(
      name: "InitializableUpgradeabilityProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InitializableUpgradeabilityProxy>;
    getContractAt(
      name: "Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "UpgradeabilityProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradeabilityProxy>;
    getContractAt(
      name: "BasicAdapter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BasicAdapter>;
    getContractAt(
      name: "ERC20WithPermit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20WithPermit>;
    getContractAt(
      name: "ERC20WithRate",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20WithRate>;
    getContractAt(
      name: "GatewayFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GatewayFactory>;
    getContractAt(
      name: "GatewayRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GatewayRegistry>;
    getContractAt(
      name: "IERC20Standard",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Standard>;
    getContractAt(
      name: "IBurnGateway",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBurnGateway>;
    getContractAt(
      name: "IGateway",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGateway>;
    getContractAt(
      name: "IMintGateway",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IMintGateway>;
    getContractAt(
      name: "IGatewayRegistry",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGatewayRegistry>;
    getContractAt(
      name: "BCHGateway",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BCHGateway>;
    getContractAt(
      name: "BTCGateway",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BTCGateway>;
    getContractAt(
      name: "MintGatewayLogicV1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MintGatewayLogicV1>;
    getContractAt(
      name: "MintGatewayStateV1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MintGatewayStateV1>;
    getContractAt(
      name: "ZECGateway",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZECGateway>;
    getContractAt(
      name: "MintGatewayLogicV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MintGatewayLogicV2>;
    getContractAt(
      name: "MintGatewayProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MintGatewayProxy>;
    getContractAt(
      name: "MintGatewayStateV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MintGatewayStateV2>;
    getContractAt(
      name: "RenERC20LogicV1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RenERC20LogicV1>;
    getContractAt(
      name: "RenERC20Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RenERC20Proxy>;
    getContractAt(
      name: "Claimable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Claimable>;
    getContractAt(
      name: "CanReclaimTokens",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CanReclaimTokens>;
    getContractAt(
      name: "LinkedList",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LinkedList>;
    getContractAt(
      name: "Adapter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Adapter>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
